import {
  FileText,
  Lock,
  LockOpen,
  Image as LucideImage,
  ImageOff,
  Table as LucideTable,
  TableProperties,
  Link as LucideLink,
  Unlink,
  Columns2,
  Columns3,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Settings,
  Sliders,
  Ruler,
  Maximize2,
  Minimize2,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  Undo2,
  Redo2,
  Printer,
  RemoveFormatting,
  Heading1,
  Heading2,
  Heading3,
  List,
  ListOrdered,
  ListTodo,
  Quote,
  Code,
  Minus,
  WrapText,
  Search,
  Replace,
  Eye,
  ZoomIn,
  ZoomOut,
  RectangleVertical,
  RectangleHorizontal,
  SeparatorHorizontal,
  PanelLeftClose,
  ChevronDown,
  Check,
  X,
  Palette,
  Highlighter,
  BookOpen,
  RotateCcw,
  Sparkles,
  Scaling,
  Trash2,
  Rows3,
  Merge,
  Split,
  Square,
  Paintbrush,
  AlignHorizontalDistributeCenter,
  Sigma,
  AArrowUp,
  AArrowDown,
  CaseUpper,
  MoveVertical,
  ArrowUpDown,
  ArrowUpToLine,
  ArrowDownToLine,
  ArrowLeftToLine,
  ArrowRightToLine,
  AlignVerticalJustifyStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  Grid2X2,
  Baseline,
  ClipboardPaste,
  Copy,
  Scissors,
  PaintRoller,
  Eraser,
  IndentIncrease,
  IndentDecrease,
  ArrowDownAZ,
  MousePointerClick,
  FilePlus2,
  FileCode2,
  CodeXml,
  CornerDownLeft,
  Calendar,
  Globe,
  Maximize,
  type IconNode,
} from 'lucide';

/**
 * Renderiza un nodo de Lucide icon directamente como string SVG inline.
 * Utiliza los iconos descargados localmente desde el paquete 'lucide' (sin CDN).
 * Incluye dimensiones explícitas y clases para evitar distorsiones o colapsos.
 */
export function lucideSvg(
  node: IconNode,
  size = 14,
  className = 'cde-tb-icon',
): string {
  const children = node
    .map(
      ([tag, attrs]) =>
        `<${tag} ${Object.entries(attrs)
          .map(([k, v]) => `${k}="${v}"`)
          .join(' ')}/>`,
    )
    .join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="${className}" style="display:inline-block;vertical-align:middle;flex-shrink:0;width:${size}px;height:${size}px;">${children}</svg>`;
}

export {
  FileText,
  Lock,
  LockOpen,
  LucideImage,
  ImageOff,
  LucideTable,
  TableProperties,
  LucideLink,
  Unlink,
  Columns2,
  Columns3,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Settings,
  Sliders,
  Ruler,
  Maximize2,
  Minimize2,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  Undo2,
  Redo2,
  Printer,
  RemoveFormatting,
  Heading1,
  Heading2,
  Heading3,
  List,
  ListOrdered,
  ListTodo,
  Quote,
  Code,
  Minus,
  WrapText,
  Search,
  Replace,
  Eye,
  ZoomIn,
  ZoomOut,
  RectangleVertical,
  RectangleHorizontal,
  SeparatorHorizontal,
  PanelLeftClose,
  ChevronDown,
  Check,
  X,
  Palette,
  Highlighter,
  BookOpen,
  RotateCcw,
  Sparkles,
  Scaling,
  Trash2,
  Rows3,
  Merge,
  Split,
  Square,
  Paintbrush,
  AlignHorizontalDistributeCenter,
  Sigma,
  AArrowUp,
  AArrowDown,
  CaseUpper,
  MoveVertical,
  ArrowUpDown,
  ArrowUpToLine,
  ArrowDownToLine,
  ArrowLeftToLine,
  ArrowRightToLine,
  AlignVerticalJustifyStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  Grid2X2,
  Baseline,
  ClipboardPaste,
  Copy,
  Scissors,
  PaintRoller,
  Eraser,
  IndentIncrease,
  IndentDecrease,
  ArrowDownAZ,
  MousePointerClick,
  FilePlus2,
  FileCode2,
  CodeXml,
  CornerDownLeft,
  Calendar,
  Globe,
  Maximize,
};
